### ISSUE TITLE
連合艦隊の編成キャプチャが出来ない

### ISSUE THREAD

**Issue by xia-sava** [KanCraft/kanColleWidget#1126]
# 問題の概要

連合編成キャプチャモードで「まとめて編成キャプチャをつくる」ボタンを押しても反応がなく，
Console で以下のエラーが発生している．

```
deckcapture.js:1938 Uncaught (in promise) DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'capture_1595406500502' exceeded the quota.
    at TempStorage.store (chrome-extension://egkgleinehaapbpijnlpbllfeejjpceb/dest/js/deckcapture.js:1938:22)
    at DeckCaptureView.<anonymous> (chrome-extension://egkgleinehaapbpijnlpbllfeejjpceb/dest/js/deckcapture.js:2927:42)
    at step (chrome-extension://egkgleinehaapbpijnlpbllfeejjpceb/dest/js/deckcapture.js:2822:23)
    at Object.next (chrome-extension://egkgleinehaapbpijnlpbllfeejjpceb/dest/js/deckcapture.js:2803:53)
    at fulfilled (chrome-extension://egkgleinehaapbpijnlpbllfeejjpceb/dest/js/deckcapture.js:2794:58)
```

# 問題の再現方法

1. 「連合編成キャプチャ」モードで編成キャプチャを開始する
2. F12 で Developer Console を開いておく
3. **異なる**画像6枚～12枚をセットする
4. 「編成キャプチャをつくる」ボタンを押しても画面上では反応がなく，コンソールにエラーが出ている

# 不明点

1. 同一画像12枚だと正常な挙動でしたが，偶然かもしれない
2. 6枚未満だと正常な挙動でしたが，環境によったりするのかもしれない

# 環境

- OS: Windows10
- Chrome: 84
- 艦これウィジェット: 3.0.0-alpha80

**Comment by otiai10** [comment]
`unlimitedStorage` で解決したと思ってたんですが、ううむ

**Comment by otiai10** [comment]
画像の容量に起因します
